# Generated by Django 2.2.3 on 2019-09-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('description', models.TextField()),
                ('certification', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media/img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Category')),
            ],
        ),
    ]
